### ISSUE TITLE
checkstyle fails on mapper generated implementations 

### ISSUE THREAD

**Issue by noah-iam** [mapstruct/mapstruct-examples#108]
I love this mapstruct. I am using the 1.4.0.beta version . So , checkstyle is failing in autogenerated mapper impl 

`  <module name="WhitespaceAfter">` 

Description: When mapstruct is generating the source code, it doesn't follow the checkstyle rules .   

Solution: Although, I have suppressed the error by marking mapper implementation folder checks none but can someone take it on?

**Comment by thunderhook** [comment]
@noah-iam Is this still an issue? It seems like this is a configuration issue of checkstyle with generated sources, see https://stackoverflow.com/a/48618394 for example.

**Comment by filiphr** [comment]
Thanks for checking this one @thunderhook. To add a bit more info. There is https://github.com/mapstruct/mapstruct/issues/877 which is about using a custom formatter to format the generated code. It hasn't been done since it is not the most trivial.

 I'll close this in favor of https://github.com/mapstruct/mapstruct/issues/877
